// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aklstpvnkbdlxozghbkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbHN0cHZua2JkbHhvemdoYmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwODEwODYsImV4cCI6MjA1MjY1NzA4Nn0.n5PvQLm8Zp9X3mh5_u_N2gmShXehezYliBEgCzHoI1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);